#!/bin/bash

python -m pip install numpy



export TORCH_CUDA_ARCH_LIST="{E5v2,E5v3,Fidis,s6g1}"
export TORCH_CUDA_ARCH_LIST="{5.0, 5.2, 5.3, 6.0, 6.1, 6.2, 7.0, 7.2, 7.5, 8.0, 8.6, 8.7, 8.9, 9.0}"
export IABN_FORCE_CUDA=1

# conda install pytorch=1.8.1+cu111 torchvision=0.9.1+cu111 torchaudio pytorch-cuda=11.1 -c pytorch -c nvidia
# conda install pytorch==1.8.1 torchvision==0.9.1 pytorch-cuda=11.1 -c pytorch -c nvidia

conda create --name DLAV2 python=3.6.9
conda activate DLAV2
conda install -c anaconda cudatoolkit
python -m pip install torch==1.8.1+cu111 torchvision==0.9.1+cu111 -f https://download.pytorch.org/whl/torch_stable.html

tensorboardX~=2.1 torch~=1.8.1+cu111 setuptools~=39.0.1 opencv-python~=4.5.1.48 umsgpack~=0.1.0 numpy~=1.21 torchvision~=0.9.1+cu111 Pillow~=9.0.0 configparser~=5.0.1 kornia~=0.2.0

# Python 3.6.9 does not support the said numpy, pillow versions

tensorboardX torch setuptools umsgpack numpy torchvision Pillow configparser kornia opencv-python


# Jupyter: https://scitas-data.epfl.ch/confluence/display/DOC/Using+Jupyter

sm_50, sm_52 and sm_53	Maxwell support
sm_60, sm_61, and sm_62	Pascal support
sm_70 and sm_72	Volta support
sm_75	Turing support
sm_80, sm_86 and sm_87	Ampere support
sm_89	Ada support
sm_90, sm_90a


module load cuda/11.1.1
module load gcc/8.4.0-cuda python/3.7.7
conda create --name DLAV python=3.7.7
conda activate DLAV
conda install -c anaconda cudatoolkit
conda install pytorch torchvision torchaudio pytorch-cuda=11.7 -c pytorch -c nvidia
python -m pip install tensorboardX setuptools opencv-python umsgpack numpy Pillow configparser kornia